export * from './categoria.interface';
export * from './cliente.interface';
export * from './orden-item.interface';
export * from './orden.interface';
export * from './payload.interface';
export * from './producto.interface';
export * from './proveedor.interface';
export * from './rol.interface';
export * from './user.interface';
